### ISSUE TITLE
Fluentbit install step 3 needs more clarity 

### ISSUE THREAD

**Issue by imtrahman** [aws-samples/eks-security-compromised-cluster-remediation#11]
https://github.com/aws-samples/eks-security-compromised-cluster-remediation/blob/main/Identification/attack-discovery/fluentbit.md

Run the following command to create a ConfigMap named cluster-info with the cluster name and the region to send logs. Replace cluster-name and cluster-region with your cluster's name and Region.

#set the following environment variables using the appropriate ClusterName and RegionName
ClusterName=security-workshop
RegionName=us-east-1
FluentBitHttpPort='2020'
FluentBitReadFromHead='Off'
[[${FluentBitReadFromHead} = 'On']] && FluentBitReadFromTail='Off'|| FluentBitReadFromTail='On'
[[-z ${FluentBitHttpPort}]] && FluentBitHttpServer='Off' || FluentBitHttpServer='On'
kubectl create configmap fluent-bit-cluster-info \
        --from-literal=cluster.name=${ClusterName} \
        --from-literal=http.server=${FluentBitHttpServer} \
        --from-literal=http.port=${FluentBitHttpPort} \
        --from-literal=read.head=${FluentBitReadFromHead} \
        --from-literal=read.tail=${FluentBitReadFromTail} \
        --from-literal=logs.region=${RegionName} \
        -n amazon-cloudwatch

In the previous command, FluentBitHttpServer for monitoring plugin metrics is on by default. To turn it off, change the third line in the command to FluentBitHttpPort=""" (an empty string) in the command. Also by default, Fluent Bit reads log files from the tail, and will only capture logs created after the DeamonSet was deployed. If you want the opposite, set FluentBitReadFromHead="On" and it will collect all logs in the file system

So do we really need to turn it off, it's kind of confusing  ? 

I'd suggest add it only if it's needed for the workshop else remove it.

**Comment by jicowan** [comment]
Change region to `us-west-2` so there's one less thing to update.
