### ISSUE TITLE
kubectl apply commands in gatekeeper readme require folder execution location

### ISSUE THREAD

**Issue by rajarshidas** [aws-samples/eks-security-compromised-cluster-remediation#14]
Something like : :point_right: The following two commands need to be executed from the following folder: *eks-security-compromised-cluster-remediation/Implement_Countermeasures/gatekeeper*

before section ** Install Constraint Templates **

File: https://github.com/aws-samples/eks-security-compromised-cluster-remediation/blob/main/Implement_Countermeasures/gatekeeper/README.md

**Comment by jicowan** [comment]
Fix by #16
