### ISSUE TITLE
fluent-bit install step 4 needs to be after 

### ISSUE THREAD

**Issue by imtrahman** [aws-samples/eks-security-compromised-cluster-remediation#15]
This needs to be above step 5 

The above steps create the following cluster resources:</p>

Resource Kind | Resource Name | Resource Use
-- | -- | --
NameSpace | amazon-cloudwatch | contains fluent-bit resources
DaemonSet | fluent-bit | Contains the Pods that run Fluent Bit
ConfigMap | fluent-bit-config | Contains the configuration to be used by Fluent Bit.
ServiceAccount | fluent-bit | Used to run Fluent Bit
ClusterRole | fluent-bit-role | Grants get, list, and watch permissions on pod logs to the Fluent-Bit service account.
ClusterRoleBinding | fluent-bit-role-binding | Binds the fluent-bit ServiceAccount to the fluent-bit-role

**Comment by jicowan** [comment]
Fixed by https://github.com/aws-samples/eks-security-compromised-cluster-remediation/commit/f863319b5b42ce5a13a7e0a5db768ca576b33dd0
