### ISSUE TITLE
Error when issuing kubectl cordon command

### ISSUE THREAD

**Issue by channaba** [aws-samples/eks-security-compromised-cluster-remediation#19]
Receiving error as below,when trying cordon command as below on Cloud9 CLI

kubectl cordon carts-db-6c6c68b747-sf4xd 
--
Error from server (NotFound): nodes "carts-db-6c6c68b747-sf4xd" not found
--

Though the same pod is showing up as running on pod list command

kubectl get pods --all-namespaces | grep  Running
--
sock-shop     carts-db-6c6c68b747-sf4xd                         1/1     Running   0          3h17m
...
--

**Comment by jicowan** [comment]
@channaba you can only cordon a node. You can't cordon a pod.
