### ISSUE TITLE
Polaris chapter refers to nonexistent namespace

### ISSUE THREAD

**Issue by mifisignal** [aws-samples/eks-security-compromised-cluster-remediation#25]
The Polaris chapter refers to and provides images of selecting a "privileged" namespace -- among other namespaces that don't exist in the provisioned cluster when they visit this chapter (including "hostpath", "hostpid", etc.).

It'd be ideal if we could illustrate to the attendees how to quickly focus on the most severe security issues, and/or filter out non-security-related problems.

**Comment by jicowan** [comment]
updated images.
