### ISSUE TITLE
typos in falco Readme

### ISSUE THREAD

**Issue by rajarshidas** [aws-samples/eks-security-compromised-cluster-remediation#3]
File: https://github.com/aws-samples/eks-security-compromised-cluster-remediation/blob/main/Implement_Countermeasures/falco/README.md

Running multiple containers on **_the_** same host exposes the platform to different security threats like container breakouts, noisy neighbor and DOS, among others. As the popularity of containers and Kubernetes continues to grow, it is increasingly important to have a runtime solution in place to mitigate security threats to your environment. Technologies like gVisor and Kata Container try to isolate containers by ~~sandoxing~~ sandboxing them, however, this approach has a few limitations as well as performance issues. In this workshop we will look at Falco which ensures that containers adheres to a pre-defined set of security standards and quickly remediates potential security threats.

**Comment by jicowan** [comment]
PR was submitted to fix this
