### ISSUE TITLE
Fluentbit Installation process step 2 --region missing

### ISSUE THREAD

**Issue by imtrahman** [aws-samples/eks-security-compromised-cluster-remediation#6]
aws eks describe-cluster --name security-workshop --query "cluster.identity.oidc.issuer" --output text
You must specify a region. You can also configure your region by running "aws configure".

replace it with
 aws eks describe-cluster --name security-workshop --query "cluster.identity.oidc.issuer" --output text --region us-west-2
https://oidc.eks.us-west-2.amazonaws.com/id/B49A06FE610EF423F41D284724548AE1

**Comment by jicowan** [comment]
Fixed by https://github.com/aws-samples/eks-security-compromised-cluster-remediation/pull/2
