### ISSUE TITLE
Fluent install step 2

### ISSUE THREAD

**Issue by imtrahman** [aws-samples/eks-security-compromised-cluster-remediation#7]
replace cluster name with the correct one rather than example : 

Current one : 
eksctl create iamserviceaccount \
--cluster example \
--namespace amazon-cloudwatch \
--name fluent-bit \
--attach-policy-arn arn:aws:iam::aws:policy/CloudWatchFullAccess \
--override-existing-serviceaccounts \
--approve

Replace with : 

eksctl create iamserviceaccount \
--cluster security-workshop \
--namespace amazon-cloudwatch \
--name fluent-bit \
--attach-policy-arn arn:aws:iam::aws:policy/CloudWatchFullAccess \
--override-existing-serviceaccounts \
--approve

**Comment by jicowan** [comment]
Fixed by https://github.com/aws-samples/eks-security-compromised-cluster-remediation/pull/2
